### ISSUE TITLE
Finalize Responsibilties for Group

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#11]
We should figure out who's doing what. Following the Write-up proposal, these are the options:

A. 2 Developers - Layout and frontend design (login, home, and digital business card layouts, speech recognition, etc.).
B. 2 Developers - Application backend (database management, user sessions, routes, dynamic creation of web pages, etc.).
C. 1 Developer - Settings and accessibility feature creation.

Payton and Shane volunteered to do the Back-end (B), so that leaves me(Sterly), Leah, and Nisha to decide who's doing the rest of it.

**Comment by thadakn1** [comment]
yeah that works for me but i think it might also need some group input on
what accessibility features etc if we're doing a lot. if it's definitely a
lot of features i'll reach out to u frontend guys too. but all good for
now.

**Comment by sderacy** [comment]
Yea depending on what I'd be doing I'd be happy to tackle some of the tasks with you.

Looks like we're probably good though so I'll close this issue
