### ISSUE TITLE
Restructure Settings Page

### ISSUE THREAD

**Issue by thadakn1** [sderacy/gooncard#117]
- re-design the settings page while allowing the functionality to remain untouched.

**Comment by sderacy** [comment]
I looked into implementing a better settings page, and while I have found some good examples that we can base our settings page off of, I don't think implementing them would be a good use of our time. If we intended to have this as a desktop app, having a more intuitive interface for computer users would make sense, but most good designs will default back to the format we currently have on a mobile screen.

Keeping this in mind, I vote to close this issue as I don't think this a problem that needs fixing or a problem that is worth our time.

What do you think? @thadakn1 @matyis1 @thadakn1 @paytonshaltis

**Comment by thadakn1** [comment]
I think you are completely right, I’ve been kinda wracking my brain trying to think about how we could possibly restructure it so it looks better for the mobile view but it doesn’t seem to be worth it. It works and it’s simple and at the end of the day I think that’s all that matters. I really did try to think about how we can make it more appealing to the eye though but I don’t think it’s a pressing concern. Anything I can think of really just involved background changes and the formatting of the fields but they look fine on the mobile view. 

That being said, I think you should keep the issue open because I’m working on the “button that allows users to delete their goon card account” and the modal. I did some work today but need more time. So please don’t close it for that reason. I will try to work on it earlier this week hopefully.
