### ISSUE TITLE
Change font size naming for Settings page

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#129]
It's set to "smaller, medium, larger" because that's the name of the values that are being applied to font size, but replacing with something more readable might be better for the user

**Comment by lelekaz** [comment]
> It's set to "smaller, medium, larger" because that's the name of the values that are being applied to font size, but replacing with something more readable might be better for the user
![IMG_6070](https://user-images.githubusercontent.com/57500218/201212818-0d695373-2945-4337-a874-be083eaed667.PNG)
I looked at my kindle app for ideas; maybe something like this could suffice?
