### ISSUE TITLE
Settings changes should show up right away.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#133]
In the settings page, when a user changes a setting, the page should change immediately in order to show the user the effect of their setting changes.

**Comment by sderacy** [comment]
Does it not currently do this?

**Comment by paytonshaltis** [comment]
> Does it not currently do this?

I mean before they click submit. That way they can see a preview of what the site will look like for them before actually committing to the settings changes.

**Comment by sderacy** [comment]
Go for it, let me know what you think of the bug regarding the default styling we talked about in class.

That's the only real issue I see with my implementation so if we can find a solid fix to the refresh bug, it's probably ready to go.
