### ISSUE TITLE
Default Styling set to Dark Mode

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#134]
This is an issue because if you select light mode as your preferred theme, some pages will start with the dark mode color scheme and then change to the light mode color scheme. It can look pretty jarring.

You can argue that my implementation might not have been the best but I think there's a more general issue of how to serve the pages to the user only after the settings have been applied to the page. Solving this issue would solve the bug here.

**Comment by paytonshaltis** [comment]
> This is an issue because if you select light mode as your preferred theme, some pages will start with the dark mode color scheme and then change to the light mode color scheme. It can look pretty jarring.
> 
> You can argue that my implementation might not have been the best but I think there's a more general issue of how to serve the pages to the user only after the settings have been applied to the page. Solving this issue would solve the bug here.

Definitely will need to apply the settings via the EJS file if we want the correct page defaults to be sent to the user.
