### ISSUE TITLE
Warn users before they navigate to another page if they've made changes

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#137]
Currently, if the user clicks to another page from profile or settings, it will actually just let them do so and lose all their changes. It should give them a choice to confirm this so that they don't lose any data accidentally.

**Comment by paytonshaltis** [comment]
Will probably want to look at the [beforeUnload()](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) event handler.

**Comment by sderacy** [comment]
I was literally gonna say the same thing:
https://stackoverflow.com/questions/1119289/how-to-show-the-are-you-sure-you-want-to-navigate-away-from-this-page-when-ch
