### ISSUE TITLE
Reduce margins, all-around mobile style check.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#157]
Some pages on mobile screens have pretty large margins, to the point where there is more space on the left and right side of the text than there is actual horizontal room for text. Some examples of this are on the about page and the home page when a user has no accounts. 

We should probably make it a point to try looking through all variations of all pages in order to make sure that things look good on mobile. Please feel free to comment on this issue about things that you see on mobile that don't look quite right, and we will just keep modifying the list and working to get everything looking good.

Currently, we have:
- Reduce margins on pages (should check page-by-page)
- Still some collision issues with the footer on mobile (go to the profile page and rotate your phone horizontally).
- Home screen buttons may need some margin between them for when the flexbox wraps.

Also feel free to convince me otherwise on any of these issues; if something I mention was intended, no problem at all.

**Comment by sderacy** [comment]
> Some pages on mobile screens have pretty large margins, to the point where there is more space on the left and right side of the text than there is actual horizontal room for text. Some examples of this are on the about page and the home page when a user has no accounts.

I'm personally planning on looking at the styling for the pages once Nisha adds her help pages since that'll be the last big feature we're probably implementing.

> Currently, we have:
> * Reduce margins on pages (should check page-by-page)
> * Still some collision issues with the footer on mobile (go to the profile page and rotate your phone horizontally).
> * Home screen buttons may need some margin between them for when the flexbox wraps.

Regarding the second bullet point, are we trying to provide styling for landscape mode? I'm not concerned about wider screens because desktops and tablets seem to work just fine, but it looks like there's a special issue when the user rotates their phone horizontally. This could complicate the styling by a considerable amount.

I agree with the other issues though and figured they'd be covered in #146

**Comment by paytonshaltis** [comment]
> Regarding the second bullet point, are we trying to provide styling for landscape mode? I'm not concerned about wider screens because desktops and tablets seem to work just fine, but it looks like there's a special issue when the user rotates their phone horizontally. This could complicate the styling by a considerable amount.

Not necessarily landscape mode, but anytime the user reduces the window height of their browser. Here's a screenshot of it running on Safari:

Interestingly, the footer never collides with content on the home or about pages, so this may just be as simple as checking out the settings and profile pages to see why collision sometimes occurs. It doesn't seem to be an issue on Chrome, but that footer (especially the hoverable Goon Squad part) looks very different on Safari on Mac and iPhone...

**Comment by sderacy** [comment]
Fair point. I tried to add something to see if it fixed it but I can't be too sure. Let me know how it looks on your end.

I also noticed some discrepancies between different browsers on the mobile version. At least for the sake of the demo, we can just tell Dr. Salgian that Chrome is the most supported version and use that browser when showing off the app.

**Comment by paytonshaltis** [comment]
Yeah I agree. Not really enough time this semester to try and make sure that every browser works correctly.
