### ISSUE TITLE
Handles on displaycard Page need to Link to actual sites

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#159]
Dr. Salgian liked our card page (I think at least), but it sounded like we should have the user navigate to a specific page when a social media handle is tapped on.

**Comment by thadakn1** [comment]
do you mean like the account they include should be clickable so it redirects them to the app on their phone and directly to their page?

**Comment by sderacy** [comment]
Sorta, I think it would make more sense if the entire white bar or field was clickable and redirected them to the page if possible.

**Comment by paytonshaltis** [comment]
If we do this, it means anytime someone wants to add an account, they will need to add it it full so we can put it in an anchor tag that redirects to the site. For example, we would need to replace `@paytonshaltis` for the Instagram account with `https://www.instagram.com/paytonshaltis/`

**Comment by thadakn1** [comment]
@paytonshaltis i was thinking the exact same thing, then the app fails to be as user-friendly as we were originally thinking. it's not that efficient to have the user enter their entire url for each platform like that. but i guess on the reciever side (person who scans the code), it'll be easier for them to navigate to the user's profile instead of typing it into the search bar of whatever platform they're on. 

i personally like it the way it is, but i can see how the addition above could make it easier for the person who scans the QR code. is there any way to accomplish both you think?

**Comment by sderacy** [comment]
> @paytonshaltis i was thinking the exact same thing, then the app fails to be as user-friendly as we were originally thinking. it's not that efficient to have the user enter their entire url for each platform like that

I agree with Nisha here. I think we can explain to Salgian that in order to implement this fully, we'd have to encompass the routing for every different account. If there's a way to know how the routing works for most platforms, we can just have a base string and append the username to it.

Something like `https://www.instagram.com/` and then append `paytonshaltis` or "https://www.linkedin.com/" and append `paytonshaltis`. This is a complicated problem because there's no easy way to do this routing without sanitizing the input or making sure the value is pre-formatted when it's entered.

I'd like to believe Salgian would understand this but I'm open to hearing what you guys think.

**Comment by lelekaz** [comment]
In one of my latest commits, I added functionality that allows the user to click on the white div to redirect if the value is detected as a url.
I think we just leave it to the user to do whatever they want. If they want to do "Leah Kazenmayer" for their LinkedIn for example, then the value will just be that, "Leah Kazenmayer". If they personally want the link, then they put in "https://www.linkedin.com/in/leah-kazenmayer/", then they can and the code will detect it as a link and wrap it in an a element. That's the functionality that it has as of right now; just letting it be customizable for the user.

**Comment by thadakn1** [comment]
that's super clever! this way we're not forcing the user to enter any specific kind of format for the accounts and if they happen to include a url, it'll be easy for the "receiver" to navigate to their profile. this is definitely a good work around. i think we should go with this approach. it really is that happy in-between approach we can work with especially with the time constraint. i haven't tested it out on my end yet, but i will as soon as i push my help modal changes up tonight and pull your commit.

**Comment by sderacy** [comment]
+1. Nice job Leah!

**Comment by lelekaz** [comment]
Just as a side note, the url needs to have the http:// or https:// in front to make it a valid url. We can adjust this as needed.

**Comment by paytonshaltis** [comment]
This is the right move I think. Our original design documents didn't really explicitly say that we would have links: it's a dynamic business card, after all. But for sure, if the user wants to add a link, I think having the functionality as @lelekaz implemented it is the right way to go. Again, simple features for new users, and advanced features for expert users.
