### ISSUE TITLE
Confirm display card page preview.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#167]
I just wanted to confirm that everything on the display card was working as intended... I think @lelekaz this was you? I'm attaching a screenshot of what it looks like right now.
- Is the text supposed to overflow like this on mobile? I know that it's all technically one single word, but is there any way to potentially wrap this onto another line? Or maybe accounts that are links could just show the account name?
- The links work great. Should there be some kind of visualization though to let the user know that they are links? Maybe just the default blue color and underline?

Let me know what you all think about these changes. Just want to make sure that we are getting all of these small things covered before we submit the final version of the code!

**Comment by lelekaz** [comment]
For links I can make them underlined in white to show that it is a link if you'd like!

And I believe that if the link is too long, it automatically wraps to the next line; is there an instance where it goes past the borders of the div? Is this what you mean?

**Comment by paytonshaltis** [comment]
Haha totally forgot to attach it... here it is now:

![IMG_2866 (1)](https://user-images.githubusercontent.com/57500301/205421847-eea13405-204e-49c0-9bf8-6076d62e2831.PNG)

**Comment by lelekaz** [comment]
> Haha totally forgot to attach it... here it is now:
> 
> ![IMG_2866 (1)](https://user-images.githubusercontent.com/57500301/205421847-eea13405-204e-49c0-9bf8-6076d62e2831.PNG)

That's so strange...for my phone it automatically breaks. But I can try to force the break, but I don't know whether I'll be able to see it on my end if I actually fix it 😂.
![IMG_6197](https://user-images.githubusercontent.com/57500218/205424661-27809f43-bf4e-4d26-af00-4ab1d9a2d048.PNG)
