### ISSUE TITLE
Move aboutus.ejs to its own subdirectory like the other pages.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#36]
A small change should be made to keep the consistency of our directory structure... may also want to see if any other views added between making this issue and resolving it are doing the same thing.

**Comment by sderacy** [comment]
This was intentional because I don't think it warrants needing its own directory. I envisioned the about us page to host a body of text and not really having a need for any special CSS or scripting since it's gonna be pretty static.

Let me know if you think otherwise though

**Comment by paytonshaltis** [comment]
I agree that it probably won't need CSS or JS, but I just think it can get confusing if we start having multiple EJS files per folder... each folder I think should logically represent one page of the app and everything required for it. Makes it easier for adding content later in case we decide that we _do_ need to add custom CSS or JS.

**Comment by sderacy** [comment]
Gotcha, then I can tackle this along with another issue I have in mind
