### ISSUE TITLE
Allow user to choose which links they wish to share

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#5]
User must be able to customize which social media pages they would like to share

For example, a user can choose to share either casual social media pages like Instagram or Twitter, or more professional alternatives such as LinkedIn.

There could also just simply be an option to allow them to manually toggle what they want to share.

**Comment by paytonshaltis** [comment]
This issue should also implement the front-end functionality for toggling all professional and casual accounts at a time using the buttons at the top of the home page. The toggles will need to be visually toggled, as well as the ids for each row stored in the `toggled` array as is already done in the `main.js` file.
