### ISSUE TITLE
Allow user to scan QR code and navigate to page in website

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#6]
User must be able to scan the generated QR code from another user and be navigated to a page to view the social media links

I think that if this is implemented with the native QR reader, we shouldn't have to do anything once the qr code has been generated since it should just navigate to a specific web page.

The QR code link should be generated with a UUID so it's very unlikely that two links will go to the same spot.

**Comment by paytonshaltis** [comment]
Since we decided that the native QR code reader on users' phones will be used, there is no real need for this issue. Scanning QR codes will be implemented when #1 gets completed.
