### ISSUE TITLE
Create a field for account type when adding social media account.

### ISSUE THREAD

**Issue by paytonshaltis** [sderacy/gooncard#68]
If we are going to allow users to toggle their account visibility based on casual or professional, then the small form at the bottom of the social media accounts page that lets users add new accounts needs to have an additional dropdown that lets them choose between one of these two options.

Additionally, on this page, each row of accounts that the user can edit should also have a dropdown to change between casual or professional.

**Comment by sderacy** [comment]
So if I understand this correctly, you'd like for there to be a dropdown on the page to generate the QR code where a user can specify a casual or professional preset of social media handles.

If that's the case, I would suggest not doing a drop down but maybe the buttons that Leah currently has on the screen. I think there can be some front-end logic where when the button is clocked, it will automatically toggle the specified fields.

I wouldn't be opposed to having drop downs for the page where you add social media accounts

**Comment by paytonshaltis** [comment]
> So if I understand this correctly, you'd like for there to be a dropdown on the page to generate the QR code where a user can specify a casual or professional preset of social media handles.
> 
No, the generate QR code page looks great with the buttons the way they are, I'm not suggesting any change there.

> I wouldn't be opposed to having drop downs for the page where you add social media accounts
>
This is all I'm suggesting. It doesn't even need to be a dropdown, it could be radio buttons or whatever, just some way that a user can indicate the account type when they edit and create a new social media account. When data is sent to the backend to add or edit an account, the account type just needs to be sent as well.

**Comment by sderacy** [comment]
> This is all I'm suggesting. It doesn't even need to be a dropdown, it could be radio buttons or whatever, just some way that a user can indicate the account type when they edit and create a new social media account. When data is sent to the backend to add or edit an account, the account type just needs to be sent as well.

Gotcha, that makes sense. From what I recall of the page dimensions, there's a lot of content so I would advise against something like a radio button since it'll have to resize to the mobile UI.

**Comment by paytonshaltis** [comment]
>  I would advise against something like a radio button since it'll have to resize to the mobile UI.
>
That's up to you Mr. Frontend -_-
