### ISSUE TITLE
Social Media Account toggles are inverted

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#80]
The order of the toggle divs should be:

Icon, Label, Toggle

Right now it's inverted.

**Comment by lelekaz** [comment]
> 

Do we want the faicons on the home page too? Or just the label + value?

**Comment by thadakn1** [comment]
@sderacy on the home page, can we just have the toggle and the platform name (no platform value like insta username and no Fa icon). 

it will definitely be too much content on the home page if there's also an icon. but lmk what you think!

**Comment by lelekaz** [comment]
> @sderacy on the home page, can we just have the toggle and the platform name (no platform value like insta username and no Fa icon).
> 
> it will definitely be too much content on the home page if there's also an icon. but lmk what you think!

We decided on just keeping the Account Label on the home page, correct? No value? If so, should we close this issue?

**Comment by sderacy** [comment]
I think the discussion here was that the label should be on the left side and the toggle on the right side, so if that is the current plan, this should remain open.
