### ISSUE TITLE
Speech Recognition

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#9]
So to be clear about how this would be used with our application, the idea is that the user should be able to verbally say "Generate Social" or "Generate Professional". This would generate a QR code with the social links or generate a QR code with a professional link.

We can add more later.

**Comment by thadakn1** [comment]
- finished the front-end part of just adding the button, lmk if i can do anything else!

**Comment by sderacy** [comment]
We're probably gonna have to find some text to speech api to handle the voice input next, and just have it do some operations depending on what they say.
