### ISSUE TITLE
Use a Save Changes Button for Accounts page instead of saving on Update

### ISSUE THREAD

**Issue by sderacy** [sderacy/gooncard#93]
Currently, if you change a field on the profile page it will automatically save the information. It would be nicer to have a button that sends all of the data at once instead of a couple little changes.

**Comment by paytonshaltis** [comment]
Need to create a few action arrays:
- Add: When a new entry is added, store it in this array.
- Edit: When an existing entry is edited, either:
  - If it has a valid db ID, add the updated values to this edit array. If the ID is already in the 'edit' array, overwrite it with the new edits.
  - If it does _not_ have a valid db ID, modify the associated values in the 'add' array.
- Delete: When a new entry is deleted, either:
  - If it has a valid db ID, remove it from the 'edit' array and add its ID to this array.
  - If it does _not_ have a valid db ID, simply remove it from the 'add' array.

The add, edit, and delete arrays can then be sent to the server. In any order, the new entries should by added, edited entries should be updated, and deleted entries should be removed from the database. Actions on the client side should ensure that there is no duplication between these arrays. 

Any error should return false. Posting should also refresh the page to show the modified results, and display a success message.
